In [1]:
%cd /home/adityasidharta/git/saltedge_python

/home/adityasidharta/git/saltedge_python

In [2]:
import pandas as pd
import os

import fire
import pandas as pd

from src.utils.directory import RAW_PATH

In [3]:
pd.options.display.max_rows = 100

In [4]:
def get_accounts(year, month):
    accounts = []
    for filename in os.listdir(RAW_PATH):
        if filename.endswith("_{}_{}.csv".format(year, month)):
            index = filename.index("_{}_{}.csv".format(year, month))
            account = filename[:index].split(' ')[0]
            accounts.append(account)
    return accounts

In [5]:
get_accounts(2019, 9)

['406-02088-6', '421-48697-2', '120-192381-9']

In [6]:
pd.options.display.max_columns = 200
pd.options.display.max_rows = 200

In [7]:
year = 2019
month = 9

list_df = []
for filename in os.listdir(RAW_PATH):
    if filename.endswith("_{}_{}.csv".format(year, month)):
        list_df.append(pd.read_csv(os.path.join(RAW_PATH, filename)))
full_df = pd.concat(list_df, axis=0, ignore_index=True)

In [8]:
full_df = full_df[full_df['duplicated'] == False].copy()

In [9]:
full_df.groupby('category')['amount'].sum()

category
auto_and_transport       -170.00
business_services         100.00
cafes_and_restaurants     -33.40
car_rental                -81.19
entertainment             -38.59
fees_and_charges          -44.15
food_and_dining           -10.00
groceries                 -14.60
home_supplies             -43.70
income                   1612.89
phone                     -78.99
public_transportation     -41.00
service_fee                 9.00
shopping                 -761.65
taxi                      -37.49
television                -16.98
transfer                -6671.22
transportation            -86.18
uncategorized             -38.84
Name: amount, dtype: float64

In [10]:
full_df[['id', 'account_id', 'made_on', 'amount', 'description', 'category', 'type']].sort_values('amount')

,id,account_id,made_on,amount,description,category,type
56,1801236406,9347264,2019-09-03,-4900.80,INV DBS Vickers Securities 8082719 014638061,transfer,ADV
52,1801236570,9347260,2019-09-28,-783.97,FAST / PayNow Transfer PayNow Transfer To: Wil...,transfer,ICT
7,1801236334,9347260,2019-09-02,-700.00,"39343836,BRAS BASAH",shopping,AWL
61,1801236778,9347264,2019-09-11,-492.29,TRF 406-02088-6 : I-BANK,transfer,ADV
60,1801236774,9347264,2019-09-10,-409.96,TRF 406-02088-6 : I-BANK,transfer,ADV
33,1801236494,9347260,2019-09-13,-304.96,PAYPAL *OSTAY 40 29 11SEP 4628-****-****-3836,fees_and_charges,MST
58,1801236766,9347264,2019-09-07,-100.00,TRF 406-02088-6 : I-BANK,transfer,ADV
26,1801236466,9347260,2019-09-07,-81.19,KLOOK TECHNOLOGY SI NG 05SEP 4628-****-****-3836,car_rental,MST
40,1801236522,9347260,2019-09-21,-77.53,SCOOTTFZ9 SI NG 19SEP 4628-****-****-3836 MYR2...,transportation,MST
48,1801236554,9347260,2019-09-25,-50.00,GRAB *1373********7021 SI NG 23SEP 4628-4500-3...,auto_and_transport,MST
17,1801236430,9347260,2019-09-05,-50.00,GRAB *1373********7021 SI NG 03SEP 4628-4500-3...,auto_and_transport,MST
1,1801236310,9347260,2019-09-01,-50.00,GRAB *1373********7021 SI NG 30AUG 4628-4500-3...,auto_and_transport,MST
37,1801236510,9347260,2019-09-19,-44.99,MYREPUBLIC LIMITED SI NG 17SEP 4628-****-****-...,phone,MST
6,1801236330,9347260,2019-09-01,-38.59,TICKETMASTER COM ME LB 29AUG 4628-****-****-38...,entertainment,MST
30,1801236482,9347260,2019-09-10,-37.49,UBER HELP.UBER.COM 80 05 07SEP 4628-****-****-...,taxi,MST
42,1801236530,9347260,2019-09-24,-30.82,LAZADA SINGAPORE (PAYM SI NG 21SEP 4628-****-*...,shopping,MST
43,1801236534,9347260,2019-09-24,-29.90,IKEA SI NG 21SEP 4628-****-****-3836,home_supplies,MST
62,1801236782,9347264,2019-09-15,-29.69,UMC-S ERAMAN KLIA SE PA 13SEP 5264-****-****-2...,uncategorized,POS
21,1801236446,9347260,2019-09-06,-28.00,CIRCLES.LIFE SI NG 05SEP 4628-****-****-3836,phone,MST
14,1801236418,9347260,2019-09-03,-21.98,SHOPEE - SINGAPORE SI NG 30AUG 4628-****-****-...,shopping,MST
2,1801236314,9347260,2019-09-01,-20.00,GRAB *DC45B66FBFFD4158 SI NG 30AUG 4628-****-*...,auto_and_transport,MST
25,1801236462,9347260,2019-09-07,-16.98,NETFLIX_SG_LOCAL SI NG 05SEP 4628-****-****-3836,television,MST
45,1801236542,9347260,2019-09-24,-14.60,NTUC FP-CLEMENTI A SI NG 21SEP 4628-****-****-...,groceries,MST
44,1801236538,9347260,2019-09-24,-13.80,IKEA - RESTAURANT SI NG 21SEP 4628-****-****-3836,home_supplies,MST
35,1801236502,9347260,2019-09-14,-11.03,PAYPAL *OLAAUSTRALI 40 29 12SEP 4628-****-****...,fees_and_charges,MST
10,1801236346,9347260,2019-09-03,-10.06,SHOPEE - SINGAPORE SI NG 30AUG 4628-****-****-...,shopping,MST
19,1801236438,9347260,2019-09-05,-10.00,FISH & CO SI NG 02SEP 4628-****-****-3836,food_and_dining,MST
13,1801236358,9347260,2019-09-03,-9.75,MCDONALD'S (BJ) SI NG 31AUG 4628-****-****-3836,cafes_and_restaurants,MST
22,1801236450,9347260,2019-09-06,-9.20,SUBWAY - T2 SI NG 04SEP 4628-****-****-3836,cafes_and_restaurants,MST
63,1801236786,9347264,2019-09-17,-9.15,UMC-S OTWC-KLIA (POC) SE PA 13SEP 5264-****-**...,uncategorized,POS
4,1801236322,9347260,2019-09-01,-8.85,LAZADA SINGAPORE SI NG 30AUG 4628-****-****-3836,shopping,MST
59,1801236770,9347264,2019-09-10,-8.65,UMC-S TRANSPORTFORNSW TAP SY DN 07SEP 5264-***...,transportation,POS
34,1801236498,9347260,2019-09-14,-7.34,PAYPAL *OLAAUSTRALI 40 29 12SEP 4628-****-****...,fees_and_charges,MST
12,1801236354,9347260,2019-09-03,-7.15,KFC TB 520 SI NG 02SEP 4628-****-****-3836,cafes_and_restaurants,MST
32,1801236490,9347260,2019-09-13,-6.56,PAYPAL *OLAAUSTRALI 40 29 11SEP 4628-****-****...,fees_and_charges,MST
16,1801236426,9347260,2019-09-04,-4.83,BUS/MRT 10134958 SI NG 29AUG 4628-****-****-3836,public_transportation,MST
27,1801236470,9347260,2019-09-07,-3.82,BUS/MRT 10489340 SI NG 02SEP 4628-****-****-3836,public_transportation,MST
11,1801236350,9347260,2019-09-03,-3.71,BUS/MRT 10020122 SI NG 28AUG 4628-****-****-3836,public_transportation,MST
18,1801236434,9347260,2019-09-05,-3.70,MCDONALD'S (NBR) SI NG 02SEP 4628-****-****-3836,cafes_and_restaurants,MST
15,1801236422,9347260,2019-09-04,-3.69,BUS/MRT 10228509 SI NG 30AUG 4628-****-****-3836,public_transportation,MST
36,1801236506,9347260,2019-09-14,-3.61,PAYPAL *OLAAUSTRALI 40 29 12SEP 4628-****-****...,fees_and_charges,MST
46,1801236546,9347260,2019-09-24,-3.60,MCDONALD'S (CL3) SI NG 21SEP 4628-****-****-3836,cafes_and_restaurants,MST
50,1801236562,9347260,2019-09-26,-3.05,BUS/MRT 12199032 SI NG 21SEP 4628-****-****-3836,public_transportation,MST
0,1801236306,9347260,2019-09-01,-3.00,CIRCLES.LIFE SI NG 31AUG 4628-****-****-3836,phone,MST
41,1801236526,9347260,2019-09-24,-3.00,Q ORANGE SI NG 22SEP 4628-****-****-3836,phone,MST
23,1801236454,9347260,2019-09-06,-2.90,BUS/MRT 10384165 SI NG 01SEP 4628-****-****-3836,public_transportation,MST
20,1801236442,9347260,2019-09-05,-2.86,BUS/MRT 10348536 SI NG 31AUG 4628-****-****-3836,public_transportation,MST
5,1801236326,9347260,2019-09-01,-2.70,BUS/MRT 9870536 SI NG 26AUG 4628-****-****-3836,public_transportation,MST
54,1801236578,9347260,2019-09-29,-2.68,BUS/MRT 12421472 SI NG 24SEP 4628-****-****-3836,public_transportation,MST
53,1801236574,9347260,2019-09-28,-2.68,BUS/MRT 12357321 SI NG 23SEP 4628-****-****-3836,public_transportation,MST
51,1801236566,9347260,2019-09-27,-2.58,BUS/MRT 12245946 SI NG 22SEP 4628-****-****-3836,public_transportation,MST
3,1801236318,9347260,2019-09-01,-2.51,BUS/MRT 9943798 SI NG 27AUG 4628-****-****-3836,public_transportation,MST
49,1801236558,9347260,2019-09-25,-1.96,BUS/MRT 12079256 SI NG 20SEP 4628-****-****-3836,public_transportation,MST
28,1801236474,9347260,2019-09-08,-1.03,BUS/MRT 10549821 SI NG 03SEP 4628-****-****-3836,public_transportation,MST
64,1801236790,9347264,2019-09-30,0.02,Interest Earned,income,ATINT
55,1801236582,9347260,2019-09-30,0.03,Interest Earned,income,INT
8,1801236338,9347260,2019-09-02,9.00,Standing Instruction,service_fee,SI
9,1801236342,9347260,2019-09-03,10.06,Shopee - Singapore SI NG 30AUG 4628-****-****-...,shopping,MST
57,1801236762,9347264,2019-09-07,10.59,Interest Earned,income,INT
47,1801236550,9347260,2019-09-24,15.80,DBS VISA DEBIT 3% CASHBAC K 19SEP 4628-****-**...,transfer,MST
24,1801236458,9347260,2019-09-07,100.00,120-192381-9 : I-BANK,business_services,ITR
38,1801236514,9347260,2019-09-20,289.35,PAYPAL *OSTAY 40 29 18SEP 4628-****-****-3836,fees_and_charges,MST
29,1801236478,9347260,2019-09-10,409.96,120-192381-9 : I-BANK,income,ITR
31,1801236486,9347260,2019-09-11,492.29,120-192381-9 : I-BANK,income,ITR
39,1801236518,9347260,2019-09-21,700.00,"39343836,CLEMENTI BR",income,CAM

In [11]:
full_df[~full_df.description.apply(lambda x : 'I-BANK' in x and '120-192381-9' in x)]

,index,id,account_id,duplicated,mode,status,made_on,amount,currency_code,description,category,type,account_balance_snapshot,created_at,updated_at
0,51,1801236306,9347260,False,normal,posted,2019-09-01,-3.00,SGD,CIRCLES.LIFE SI NG 31AUG 4628-****-****-3836,phone,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
1,52,1801236310,9347260,False,normal,posted,2019-09-01,-50.00,SGD,GRAB *1373********7021 SI NG 30AUG 4628-4500-3...,auto_and_transport,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
2,53,1801236314,9347260,False,normal,posted,2019-09-01,-20.00,SGD,GRAB *DC45B66FBFFD4158 SI NG 30AUG 4628-****-*...,auto_and_transport,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
3,54,1801236318,9347260,False,normal,posted,2019-09-01,-2.51,SGD,BUS/MRT 9943798 SI NG 27AUG 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
4,55,1801236322,9347260,False,normal,posted,2019-09-01,-8.85,SGD,LAZADA SINGAPORE SI NG 30AUG 4628-****-****-3836,shopping,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
5,56,1801236326,9347260,False,normal,posted,2019-09-01,-2.70,SGD,BUS/MRT 9870536 SI NG 26AUG 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
6,57,1801236330,9347260,False,normal,posted,2019-09-01,-38.59,SGD,TICKETMASTER COM ME LB 29AUG 4628-****-****-38...,entertainment,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
7,58,1801236334,9347260,False,normal,posted,2019-09-02,-700.00,SGD,"39343836,BRAS BASAH",shopping,AWL,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
8,59,1801236338,9347260,False,normal,posted,2019-09-02,9.00,SGD,Standing Instruction,service_fee,SI,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
9,60,1801236342,9347260,False,normal,posted,2019-09-03,10.06,SGD,Shopee - Singapore SI NG 30AUG 4628-****-****-...,shopping,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
10,61,1801236346,9347260,False,normal,posted,2019-09-03,-10.06,SGD,SHOPEE - SINGAPORE SI NG 30AUG 4628-****-****-...,shopping,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
11,62,1801236350,9347260,False,normal,posted,2019-09-03,-3.71,SGD,BUS/MRT 10020122 SI NG 28AUG 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
12,63,1801236354,9347260,False,normal,posted,2019-09-03,-7.15,SGD,KFC TB 520 SI NG 02SEP 4628-****-****-3836,cafes_and_restaurants,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
13,64,1801236358,9347260,False,normal,posted,2019-09-03,-9.75,SGD,MCDONALD'S (BJ) SI NG 31AUG 4628-****-****-3836,cafes_and_restaurants,MST,1058.82,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
14,65,1801236418,9347260,False,normal,posted,2019-09-03,-21.98,SGD,SHOPEE - SINGAPORE SI NG 30AUG 4628-****-****-...,shopping,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
15,66,1801236422,9347260,False,normal,posted,2019-09-04,-3.69,SGD,BUS/MRT 10228509 SI NG 30AUG 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
16,67,1801236426,9347260,False,normal,posted,2019-09-04,-4.83,SGD,BUS/MRT 10134958 SI NG 29AUG 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
17,68,1801236430,9347260,False,normal,posted,2019-09-05,-50.00,SGD,GRAB *1373********7021 SI NG 03SEP 4628-4500-3...,auto_and_transport,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
18,69,1801236434,9347260,False,normal,posted,2019-09-05,-3.70,SGD,MCDONALD'S (NBR) SI NG 02SEP 4628-****-****-3836,cafes_and_restaurants,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
19,70,1801236438,9347260,False,normal,posted,2019-09-05,-10.00,SGD,FISH & CO SI NG 02SEP 4628-****-****-3836,food_and_dining,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
20,71,1801236442,9347260,False,normal,posted,2019-09-05,-2.86,SGD,BUS/MRT 10348536 SI NG 31AUG 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
21,72,1801236446,9347260,False,normal,posted,2019-09-06,-28.00,SGD,CIRCLES.LIFE SI NG 05SEP 4628-****-****-3836,phone,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
22,73,1801236450,9347260,False,normal,posted,2019-09-06,-9.20,SGD,SUBWAY - T2 SI NG 04SEP 4628-****-****-3836,cafes_and_restaurants,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
23,74,1801236454,9347260,False,normal,posted,2019-09-06,-2.90,SGD,BUS/MRT 10384165 SI NG 01SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
25,76,1801236462,9347260,False,normal,posted,2019-09-07,-16.98,SGD,NETFLIX_SG_LOCAL SI NG 05SEP 4628-****-****-3836,television,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
26,77,1801236466,9347260,False,normal,posted,2019-09-07,-81.19,SGD,KLOOK TECHNOLOGY SI NG 05SEP 4628-****-****-3836,car_rental,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
27,78,1801236470,9347260,False,normal,posted,2019-09-07,-3.82,SGD,BUS/MRT 10489340 SI NG 02SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
28,79,1801236474,9347260,False,normal,posted,2019-09-08,-1.03,SGD,BUS/MRT 10549821 SI NG 03SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
30,81,1801236482,9347260,False,normal,posted,2019-09-10,-37.49,SGD,UBER HELP.UBER.COM 80 05 07SEP 4628-****-****-...,taxi,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
32,83,1801236490,9347260,False,normal,posted,2019-09-13,-6.56,SGD,PAYPAL *OLAAUSTRALI 40 29 11SEP 4628-****-****...,fees_and_charges,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
33,84,1801236494,9347260,False,normal,posted,2019-09-13,-304.96,SGD,PAYPAL *OSTAY 40 29 11SEP 4628-****-****-3836,fees_and_charges,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
34,85,1801236498,9347260,False,normal,posted,2019-09-14,-7.34,SGD,PAYPAL *OLAAUSTRALI 40 29 12SEP 4628-****-****...,fees_and_charges,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
35,86,1801236502,9347260,False,normal,posted,2019-09-14,-11.03,SGD,PAYPAL *OLAAUSTRALI 40 29 12SEP 4628-****-****...,fees_and_charges,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
36,87,1801236506,9347260,False,normal,posted,2019-09-14,-3.61,SGD,PAYPAL *OLAAUSTRALI 40 29 12SEP 4628-****-****...,fees_and_charges,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
37,88,1801236510,9347260,False,normal,posted,2019-09-19,-44.99,SGD,MYREPUBLIC LIMITED SI NG 17SEP 4628-****-****-...,phone,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
38,89,1801236514,9347260,False,normal,posted,2019-09-20,289.35,SGD,PAYPAL *OSTAY 40 29 18SEP 4628-****-****-3836,fees_and_charges,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
39,90,1801236518,9347260,False,normal,posted,2019-09-21,700.00,SGD,"39343836,CLEMENTI BR",income,CAM,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
40,91,1801236522,9347260,False,normal,posted,2019-09-21,-77.53,SGD,SCOOTTFZ9 SI NG 19SEP 4628-****-****-3836 MYR2...,transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
41,92,1801236526,9347260,False,normal,posted,2019-09-24,-3.00,SGD,Q ORANGE SI NG 22SEP 4628-****-****-3836,phone,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
42,93,1801236530,9347260,False,normal,posted,2019-09-24,-30.82,SGD,LAZADA SINGAPORE (PAYM SI NG 21SEP 4628-****-*...,shopping,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
43,94,1801236534,9347260,False,normal,posted,2019-09-24,-29.90,SGD,IKEA SI NG 21SEP 4628-****-****-3836,home_supplies,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
44,95,1801236538,9347260,False,normal,posted,2019-09-24,-13.80,SGD,IKEA - RESTAURANT SI NG 21SEP 4628-****-****-3836,home_supplies,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
45,96,1801236542,9347260,False,normal,posted,2019-09-24,-14.60,SGD,NTUC FP-CLEMENTI A SI NG 21SEP 4628-****-****-...,groceries,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
46,97,1801236546,9347260,False,normal,posted,2019-09-24,-3.60,SGD,MCDONALD'S (CL3) SI NG 21SEP 4628-****-****-3836,cafes_and_restaurants,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
47,98,1801236550,9347260,False,normal,posted,2019-09-24,15.80,SGD,DBS VISA DEBIT 3% CASHBAC K 19SEP 4628-****-**...,transfer,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
48,99,1801236554,9347260,False,normal,posted,2019-09-25,-50.00,SGD,GRAB *1373********7021 SI NG 23SEP 4628-4500-3...,auto_and_transport,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
49,0,1801236558,9347260,False,normal,posted,2019-09-25,-1.96,SGD,BUS/MRT 12079256 SI NG 20SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
50,1,1801236562,9347260,False,normal,posted,2019-09-26,-3.05,SGD,BUS/MRT 12199032 SI NG 21SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
51,2,1801236566,9347260,False,normal,posted,2019-09-27,-2.58,SGD,BUS/MRT 12245946 SI NG 22SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
52,3,1801236570,9347260,False,normal,posted,2019-09-28,-783.97,SGD,FAST / PayNow Transfer PayNow Transfer To: Wil...,transfer,ICT,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
53,4,1801236574,9347260,False,normal,posted,2019-09-28,-2.68,SGD,BUS/MRT 12357321 SI NG 23SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
54,5,1801236578,9347260,False,normal,posted,2019-09-29,-2.68,SGD,BUS/MRT 12421472 SI NG 24SEP 4628-****-****-3836,public_transportation,MST,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
55,6,1801236582,9347260,False,normal,posted,2019-09-30,0.03,SGD,Interest Earned,income,INT,1058.82,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
56,26,1801236406,9347264,False,normal,posted,2019-09-03,-4900.80,SGD,INV DBS Vickers Securities 8082719 014638061,transfer,ADV,59.18,2019-10-13T12:19:34Z,2019-10-13T12:19:34Z
57,27,1801236762,9347264,False,normal,posted,2019-09-07,10.59,SGD,Interest Earned,income,INT,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
58,28,1801236766,9347264,False,normal,posted,2019-09-07,-100.00,SGD,TRF 406-02088-6 : I-BANK,transfer,ADV,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
59,29,1801236770,9347264,False,normal,posted,2019-09-10,-8.65,SGD,UMC-S TRANSPORTFORNSW TAP SY DN 07SEP 5264-***...,transportation,POS,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
60,30,1801236774,9347264,False,normal,posted,2019-09-10,-409.96,SGD,TRF 406-02088-6 : I-BANK,transfer,ADV,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
61,31,1801236778,9347264,False,normal,posted,2019-09-11,-492.29,SGD,TRF 406-02088-6 : I-BANK,transfer,ADV,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
62,32,1801236782,9347264,False,normal,posted,2019-09-15,-29.69,SGD,UMC-S ERAMAN KLIA SE PA 13SEP 5264-****-****-2...,uncategorized,POS,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
63,33,1801236786,9347264,False,normal,posted,2019-09-17,-9.15,SGD,UMC-S OTWC-KLIA (POC) SE PA 13SEP 5264-****-**...,uncategorized,POS,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z
64,34,1801236790,9347264,False,normal,posted,2019-09-30,0.02,SGD,Interest Earned,income,ATINT,59.18,2019-10-13T12:19:36Z,2019-10-13T12:19:36Z